- name: Add Workstation Inventory 
  hosts: localhost
  become: no
  gather_facts: true
  vars:
    OSP_GUID: "{{ lookup('env','OSP_GUID') }}"
    OSP_DOMAIN: "{{ lookup('env','OSP_DOMAIN') }}"
    OPENTLC_ID: "{{ lookup('env','OPENTLC_ID') }}"
  tasks:
    - name: Create workstation inventory
      add_host:
        name: "workstation-{{OSP_GUID}}.{{OSP_DOMAIN}}"
        group: workstation
        ansible_ssh_private_key_file: ~/.ssh/openstack.pem
        ansible_ssh_user: cloud-user

- name: Add Workstation Inventory 
  hosts: workstation
  become: no
  gather_facts: true
  tasks:
    - name: Fetch Instance Info
      os_server_info:
        cloud: openstack
        region_name: regionOne
      register: r_os_servers

    - name: Add host
      add_host:
        name: "{{ __server.public_v4 }}"
        group:
          - "{{ __server.metadata.group }}"
          - "{{ __server.metadata.deployment_name }}"
      loop: "{{ r_os_servers.openstack_servers }}"
      loop_control:
        loop_var: __server



